Parsing options like a Scripts citizen; Using functions from Functions/Bootstrap; Made script aware of /System/Index.
git-svn-id: http://svn.gobolinux.org/tools/trunk/BuildLiveCD@4123 f1d59958-e5a9-4abf-b955-4837c4fe6600

diff --git a/bin/BuildRoot b/bin/BuildRoot
--- a/bin/BuildRoot
+++ b/bin/BuildRoot
@@ -1,25 +1,45 @@
-#!/bin/sh -e
+#!/bin/bash
+
+source ScriptFunctions
+Import OptionParser
+Import GoboLinux
+Import Bootstrap
+Import Array
+
+helpOnNoArguments=yes
+scriptDescription="Automated program compilation tool."
+scriptCredits="(C)2003-2009 by Hisham Muhammad et al. Released under the GNU GPL."
+scriptUsage="<program> <options> -- <packagelist1> [packagelist2] ..."
+
+Add_Option_Entry "r" "root" "Root directory to populate."
+Add_Option_Entry "p" "packagedir" "Directory containing the binary packages."
+Add_Option_Boolean "i" "use-system-index" "Generate a tree using the /System/Index layout."
+
+Parse_Options "$@"
+eval `Args_To_Array packagelist`
+
+unset root
+unset packagedir
+unset usesystemindex
+
+Is_Entry "root" && root=`Entry "root"`
+Is_Entry "packagedir" && packagedir=`Entry "packagedir"`
+Boolean "use-system-index" && usesystemindex=true
+
+[ -z "$root" ] && Die "root option must be set."
+[ -z "$packagedir" ] && Die "packagedir option must be set."
+[ -d "$packagedir" ] || Die "$packagedir does not exist"
+[ -z "$packagelist" ] && Die "packagelist option must be set."
+for list in ${packagelist[@]}
+do
+   [ -f "$list" ] || Die "$list does not exist"
+done
 
 datadir="${goboPrograms}/BuildLiveCD/Current/Data"
 
-root="$1"
-shift
-packagedir="$1"
-shift
-packagelist="$1"
-packagelists="$@"
-
-if ! [ -d "$packagedir" -a -f "$packagelist" ]
-then
-   echo "Usage: BuildRoot <root> <packagedir> <packagelist1> [packagelist2] ..."
-   [ -d "$packagedir"  ] || echo "   $packagedir does not exist"
-   [ -f "$packagelist" ] || echo "   $packagelist does not exist"
-   exit 1
-fi
-
 if [ "$UID" != "0" ]
 then
-    echo "Running as superuser."
+    Log_Terse "Running as superuser."
     exec sudo -u "#0" $0 $*
 fi
 
@@ -35,24 +55,25 @@ function get_package_name() {
    [ -z "$pkg" ] && pkg=`ls $packagedir/${packagename}--* 2> /dev/null || true`
    if [ -z "$pkg" ]
    then
-      echo "*** Package $packagename $packagever could not be filled. ***" >&2
-      return 1
+      Die "*** Package $packagename $packagever could not be filled. ***" 
    fi
    if [ "`ls $packagedir/${packagename}--* | wc -l 2> /dev/null`" -gt 1 ]
    then  
-      echo "*** More than one version for $packagename available. Aborting. ***" >&2
-      return 1
+      Die "*** More than one version for $packagename available. Aborting. ***"
    fi
 
    echo "$pkg"
 }
 
-cat $packagelists | while read line
+for list in ${packagelist[@]}
 do
-   # just ensure that required packages are found
-   ret=`echo "$line" | awk {'print $1'}`
-   [ -z "$ret" ] || echo $ret | grep -q "^#" && continue
-   get_package_name "$line" > /dev/null || exit 1
+   cat $list | while read line
+   do
+      # just ensure that required packages are found
+      ret=`echo "$line" | awk {'print $1'}`
+      [ -z "$ret" ] || echo $ret | grep -q "^#" && continue
+      get_package_name "$line" > /dev/null || exit 1
+   done
 done
 
 [ $? -eq 0 ] || exit 1
@@ -89,20 +110,35 @@ function symlink_program() {
    full_path="$1"
    root=`readlink -f $2`
    gobolinks=/System/Links
+   goboindex=/System/Index
    name=$(basename $(dirname $full_path))
    version=$(basename ${full_path})
    #echo "Linking ${full_path} inside ${gobolinks}" 1>&2
    
-   do_link ${full_path}/bin ${gobolinks}/Executables
-   do_link ${full_path}/sbin ${gobolinks}/Executables
-   do_link ${full_path}/Resources/Wrappers ${gobolinks}/Executables
-   do_link ${full_path}/Resources/Tasks ${gobolinks}/Tasks
-   do_link ${full_path}/lib ${gobolinks}/Libraries
-   do_link ${full_path}/man ${gobolinks}/Manuals
-   do_link ${full_path}/info ${gobolinks}/Manuals/info
-   do_link ${full_path}/include ${gobolinks}/Headers
-   do_link ${full_path}/../Settings ${gobolinks}/../Settings
-   do_link ${full_path}/Shared ${gobolinks}/Shared
+   if [ "$usesystemindex" ]
+   then
+      do_link ${full_path}/bin ${goboindex}/bin
+      do_link ${full_path}/sbin ${goboindex}/bin
+      do_link ${full_path}/Resources/Wrappers ${goboindex}/bin
+      do_link ${full_path}/Resources/Tasks ${gobolinks}/Tasks
+      do_link ${full_path}/lib ${goboindex}/lib
+      do_link ${full_path}/man ${goboindex}/share/man
+      do_link ${full_path}/info ${goboindex}/share/info
+      do_link ${full_path}/include ${goboindex}/include
+      do_link ${full_path}/../Settings ${goboindex}/etc
+      do_link ${full_path}/Shared ${goboindex}/share
+   else
+      do_link ${full_path}/bin ${gobolinks}/Executables
+      do_link ${full_path}/sbin ${gobolinks}/Executables
+      do_link ${full_path}/Resources/Wrappers ${gobolinks}/Executables
+      do_link ${full_path}/Resources/Tasks ${gobolinks}/Tasks
+      do_link ${full_path}/lib ${gobolinks}/Libraries
+      do_link ${full_path}/man ${gobolinks}/Manuals
+      do_link ${full_path}/info ${gobolinks}/Manuals/info
+      do_link ${full_path}/include ${gobolinks}/Headers
+      do_link ${full_path}/../Settings ${gobolinks}/../Settings
+      do_link ${full_path}/Shared ${gobolinks}/Shared
+   fi
 
    [ -f "${root}${full_path}/Resources/Environment" ] && \
    ln -nfs ../../../Programs/${name}/${version}/Resources/Environment ${root}${gobolinks}/Environment/${name}--${version}
@@ -125,6 +161,10 @@ function install_package() {
    name=${base%%--*}
    version=${base#*--}
    version=`echo ${version%%--*} | sed -r 's/-r[0-9]+(p[0-9]+)?$//g'`
+   if [ "$usesystemindex" ]
+   then vardir=/Data/Variable
+   else vardir=/System/Variable
+   fi
    
    #
    # BIG FAT WARNING:
@@ -135,12 +175,12 @@ function install_package() {
    then 
       if [ "`program_md5 $name`" =  "$packagemd5" ]
       then
-         echo "Keeping $name $version..."
+         Log_Normal "Keeping $name $version..."
 
          # just keep package: md5 matches last installation
          return
       else
-         echo "Removing existing $name..."
+         Log_Normal "Removing existing $name..."
 
          # cleanup old md5 file
          rm -f "${root}"/../Checksums/$name--*
@@ -150,7 +190,7 @@ function install_package() {
    fi
    echo "$packagemd5" > "${root}"/../Checksums/$name--$version
    
-   echo "Installing $name $version..."
+   Log_Normal "Installing $name $version..."
    pushd "$root/Programs" &> /dev/null
    tar xjpf "$package"
 
@@ -160,17 +200,20 @@ function install_package() {
        rmdir $i 2> /dev/null || true
    done
    
-   # Fixes broken share->Shared instead of share->/System/Links/Shared
-   lshare="$name/$version/share"
-   [ -h "$lshare" ] && ln -nfs /System/Links/Shared "$lshare"
+   if [ ! "$usesystemindex" ]
+   then
+      # Fixes broken share->Shared instead of share->/System/Links/Shared
+      lshare="$name/$version/share"
+      [ -h "$lshare" ] && ln -nfs /System/Links/Shared "$lshare"
+   fi
 
    dsettings="$name/$version/Resources/Defaults/Settings"
    [ -d "$dsettings" ] && cp -a "$dsettings" "$name/Settings"
    dvariable="$name/$version/Resources/Defaults/Variable"
    if [ -d "$dvariable" ]
    then
-      cp -rf "$dvariable"/* /System/Variable
-      ln -s /System/Variable "$name/Variable"
+      cp -rf "$dvariable"/* $vardir
+      ln -s $vardir "$name/Variable"
    fi
    
    # Handling Unmanaged files (emulating InstallPackage)
@@ -185,7 +228,7 @@ function install_package() {
    symlink_program /Programs/$name/$version $root
 }
 
-echo "BuildRoot: Building root $root..."
+Log_Normal "BuildRoot: Building root $root..."
 
 #
 # Base Directories
@@ -197,103 +240,21 @@ function create_dir() {
    true
 }
 
-create_dir $root
-create_dir $root/System/Links/Executables
-create_dir $root/System/Links/Environment
-create_dir $root/System/Links/Libraries
-create_dir $root/System/Links/Headers
-create_dir $root/System/Links/Manuals/info
-create_dir $root/System/Links/Shared
-# create_dir $root/System/Links/Shared/misc
-create_dir $root/System/Links/Tasks
-create_dir $root/System/Settings
-create_dir $root/System/Variable
-create_dir $root/System/Variable/tmp 0 a+wt
-create_dir $root/System/Variable/log
-create_dir $root/System/Variable/mail
-create_dir $root/System/Variable/run
-create_dir $root/System/Variable/lock
-create_dir $root/System/Variable/spool
-create_dir $root/System/Variable/cache
-create_dir $root/System/Variable/empty 0 0755
-create_dir $root/System/Variable/lib
-create_dir $root/System/Variable/lib/misc
-create_dir $root/System/Kernel
-create_dir $root/System/Kernel/Boot
-create_dir $root/System/Kernel/Objects
-create_dir $root/System/Kernel/Modules
-create_dir $root/System/Kernel/Devices
-create_dir $root/System/Kernel/Status
-create_dir $root/Users
-create_dir $root/Users/root
-create_dir $root/Files
-create_dir $root/Files/Compile "0.sys" 2775
-create_dir $root/Files/Compile/Archives "0.sys" 2775
-create_dir $root/Files/Compile/Sources "0.sys" 2775
-create_dir $root/Files/Compile/Store "0.sys" 2775
-create_dir $root/Depot
-create_dir $root/Mount
-create_dir $root/Mount/.Pivot
-create_dir $root/Mount/CD-ROM
-create_dir $root/Mount/GoboLinux
-create_dir $root/Mount/Floppy
-create_dir $root/Mount/TmpFS
-create_dir $root/Mount/Media
-create_dir $root/Programs
+superuser=0
+Create_Filesystem_Tree $root 0 $usesystemindex
+Create_Device_Nodes $root
 
 #
-# Legacy Links
+# Checksum generation
 #
-create_dir $root/usr
-
-function create_link() {
-   [ -e "$2" ] || ln -nfs "$1" "$2"
-   true
-}
-
-create_link System/Kernel/Objects    $root/sys
-create_link System/Kernel/Devices    $root/dev
-create_link System/Kernel/Status     $root/proc
-create_link System/Variable          $root/var
-create_link System/Variable/tmp      $root/tmp
-# create_link System/Variable          $root/var/local
-create_link System/Links/Libraries   $root/lib
-create_link System/Settings          $root/etc
-create_link System/Links/Executables $root/bin
-create_link System/Links/Executables $root/sbin
-create_link System/Kernel/Boot       $root/boot
-create_link Mount                    $root/mnt
-create_link Mount/Media              $root/media
-create_link Files                    $root/srv
-
-create_link /System/Kernel/Modules $root/System/Links/Libraries/modules
-
-create_link .                            $root/usr/X11R6
-create_link .                            $root/usr/local
-# create_link /Files/Compile/Source $root/usr/src
-create_link ../System/Links/Executables  $root/usr/bin
-create_link ../System/Links/Headers      $root/usr/include
-create_link ../System/Links/Libraries    $root/usr/lib
-create_link ../System/Links/Manuals      $root/usr/man
-create_link ../System/Links/Executables  $root/usr/sbin
-create_link ../System/Links/Shared       $root/usr/share
-create_link ../Manuals                   $root/System/Links/Shared/man
-
-# create_link /Users $root/home
-# create_link /Users/`whoami` $root/root # that potentially creates a broken link 
-
-[ -e $root/System/Kernel/Devices/log     ] || mkfifo       $root/System/Kernel/Devices/log
-[ -e $root/System/Kernel/Devices/null    ] || mknod -m0666 $root/System/Kernel/Devices/null    c 1 3
-[ -e $root/System/Kernel/Devices/console ] || mknod -m0600 $root/System/Kernel/Devices/console c 5 1
-
 mkdir -p "${root}"/../Checksums/
 
 mksettings=`which MakeSystemSettings`
 if [ "`md5sum "$mksettings"`" =  "`cat "${root}/../Checksums/MakeSystemSettings" 2> /dev/null`" ]
 then
-   echo "Skipping MakeSystemSettings"
+   Log_Normal "Skipping MakeSystemSettings"
 else
-   echo "Running MakeSystemSettings"
+   Log_Normal "Running MakeSystemSettings"
    rm -f "${root}"/../Checksums/$name--*
    pushd $root/System/Settings &> /dev/null
    # MakeSystemSettings overwrites existing files
@@ -302,10 +263,10 @@ else
    md5sum "$mksettings" > "${root}/../Checksums/MakeSystemSettings"
 fi
 
-for packagelist in ${packagelists[@]}
+for list in ${packagelist[@]}
 do
-   echo "Installing packages from $packagelist"
-   cat $packagelist | while read line
+   Log_Normal "Installing packages from $list"
+   cat $list | while read line
    do
       name=$(echo $line | awk {'print $1'})
       version=$(echo $line | awk {'print $2'})
@@ -348,7 +309,7 @@ else
    echo "Keeping ${root}/System/Links/Environment/Cache"
 fi
 
-echo "Running ldconfig"
+Log_Normal "Running ldconfig"
 ldconfig -r ${root}
 
 # SymlinkProgram --relative is not perfect yet, but, ideally, we should call the following command
